on:
  workflow_call:

jobs:
  build-rippled:
    runs-on: ubuntu-latest
    outputs:
      commit-hash: ${{ steps.commit-hash.outputs.commit-hash }}
    steps:
      - name: Install dependencies
        run: |
          pip install -Iv conan==1.59.0
          wget https://github.com/Kitware/CMake/releases/download/v3.16.3/cmake-3.16.3-Linux-x86_64.sh
          sudo sh cmake-3.16.3-Linux-x86_64.sh --prefix=/usr/local --exclude-subdir
      - uses: actions/checkout@v3
        with:
          repository: XRPLF/rippled
          ref: develop
      - name: Grab short commit hash and store in env
        id: commit-hash
        run: echo commit-hash=$(git log -n 1 --pretty=format:"%h") >> "$GITHUB_OUTPUT"
      - name: Set up conan
        run: |
          conan profile new default --detect
          conan profile update settings.compiler.cppstd=20 default
          conan profile update settings.compiler.libcxx=libstdc++11 default
      - name: Build rippled
        run: |
          cd rippled
          conan export external/snappy snappy/1.1.9@
          mkdir build
          cd build
          conan install .. --output-folder . --build missing --settings build_type=Release
          cmake -DCMAKE_TOOLCHAIN_FILE:FILEPATH=build/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . -j $(nproc)
      - uses: actions/upload-artifact@v3
        with:
          name: node-executable
          path: ./rippled/build/rippled
